############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Write Up"
url = "writeup/"
weight = 2

[[main]]
name = "Code"
url = "https://github.com/r-s-lewis/qea3_final"
weight = 3