############# English navigation ##############

# main menu
[[main]]
name = "Overview"
url = "/"
weight = 1

[[main]]
name = "System Architecture"
url = "architecture/"
weight = 2

[[main]]
name = "Milestones"
url = "milestones/"
weight = 3

[[main]]
name = "Ethics Statement"
url = "ethics/"
weight = 4

[[main]]
name = "Codebase"
url = "https://github.com/EarlJr53/robo-barbie-jeep"
weight = 5